name: Waka Readme

on:
  push:
    branches: [main]
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs at 12 AM UTC (5:30 AM IST)
    - cron: "*/15 * * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master # this action name
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          RANGE: "last_7_days"         # last_7_days, last_30_days, today, yesterday
          PROJECTS: ""                 # deixar vazio para pegar todos os projetos
          LANGUAGES: ""                # deixar vazio para pegar todas as linguagens
          UPDATE_GRAPH: true  
